# Generated by Django 2.2.6 on 2019-10-18 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='review_images'),
            preserve_default=False,
        ),
    ]
